### ISSUE TITLE
CMS Plugins must define a render template

### ISSUE THREAD

**Issue by sandervm** [divio/aldryn-newsblog#328]
No matter what I try I can't get this package installed, I've tried it manually and with the Django CMS installer and both result in the same error (on runserver):

```
django.core.exceptions.ImproperlyConfigured: CMS Plugins must define a render template (<class 'aldryn_people.cms_plugins.PeoplePlugin'>) that exists: aldryn_people/plugins/standard/people_list.html
```

These paths exists, only they are contained by parent folders called 'boilerplates/legacy' or 'boilerplates/bootstrap3'.

So my feeling say it has to do with the setting 'ALDRYN_BOILERPLATE_NAME', which I have defined in my settings.py. But either the values 'legacy' or 'bootstrap3' are not changing anything.

What am I missing?

**Comment by cyberstar** [comment]
Hi @sandervm! 
In order to use ``aldryn-boilerplates`` you need to configure it properly as described in configuration section of readme for that package https://github.com/aldryn/aldryn-boilerplates#configuration
Note that depending on your ``Django`` version configuration will differ.

If that won't help - can you please provide package versions for aldryn-people, aldryn-newsblog, Django and aldryn-boilerplates? Also would be nice to see your settings for properties that are required to be changed while configuring ``aldryn-boilerplates``.

br

**Comment by sandervm** [comment]
Hey @cyberstar,

Sorry for the delay, but this additional config for the boilerplate was indeed what was needed. Everything works now!

This can be closed, thank you very much!
