### ISSUE TITLE
Bootstrap 4 boilerplate templates

### ISSUE THREAD

**Issue by johnfraney** [divio/aldryn-newsblog#495]
Is there any interest in adding Bootstrap 4-compatible boilerplate templates? I've been modifying the templates to be more Bootstrap 4-friendly while staying close to the Bootstrap 3 templates. Here's a preview:

![screenshot from 2018-07-27 22-54-22](https://user-images.githubusercontent.com/1728528/43351913-3e0a8174-91f0-11e8-923b-3b4e11452782.png)

I'd be happy to share them once they're finished. Let me know!

**Comment by oliashford** [comment]
We'd definitely be interested as we currently use djangocms-bootstrap4 and the aldryn-newsblog. Would be great to have more bs4 based themes to use as starting points. Thanks John!

**Comment by johnfraney** [comment]
@oliashford I've got a PR up with those templates (#496) if you'd like to take a look!

**Comment by oliashford** [comment]
Thanks John. Will take a look as soon as I get a chance. Best.
-------- Original message --------From: John Franey <notifications@github.com> Date: 30/07/2018  14:02  (GMT+00:00) To: aldryn/aldryn-newsblog <aldryn-newsblog@noreply.github.com> Cc: oliashford <oliver@compoundpartners.co.uk>, Mention <mention@noreply.github.com> Subject: Re: [aldryn/aldryn-newsblog] Bootstrap 4 boilerplate templates (#495) 
@oliashford I've got a PR up with those templates (#496) if you'd like to take a look!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/aldryn/aldryn-newsblog","title":"aldryn/aldryn-newsblog","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/aldryn/aldryn-newsblog"}},"updates":{"snippets":[{"icon":"PERSON","message":"@johnfraney in #495: @oliashford I've got a PR up with those templates (#496) if you'd like to take a look!"}],"action":{"name":"View Issue","url":"https://github.com/aldryn/aldryn-newsblog/issues/495#issuecomment-408855316"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/aldryn/aldryn-newsblog/issues/495#issuecomment-408855316",
"url": "https://github.com/aldryn/aldryn-newsblog/issues/495#issuecomment-408855316",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [aldryn/aldryn-newsblog] Bootstrap 4 boilerplate templates (#495)",
"sections": [
{
"text": "",
"activityTitle": "**John Franey**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@johnfraney",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"aldryn/aldryn-newsblog\",\n\"issueId\": 495,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"aldryn/aldryn-newsblog\",\n\"issueId\": 495\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/aldryn/aldryn-newsblog/issues/495#issuecomment-408855316"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 361983113\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by vThaian** [comment]
@johnfraney thanks for open this issue. Regarding your question, we will not support boilerplates in this manner in the future anymore. I'm closing this ticket.
